export const theme = {
  colors: {
    primary: '#2563eb',
    primaryHover: '#1d4ed8',
    danger: '#dc2626',
    dangerHover: '#b91c1c',
    background: '#f1f5f9',
    surface: '#ffffff',
    border: '#e2e8f0',
    textPrimary: '#1e293b',
    textSecondary: '#64748b',
    textMuted: '#94a3b8',
  },
  categories: {
    carne:      { bg: '#fef2f2', color: '#991b1b', label: '🥩 Carne' },
    frango:     { bg: '#fefce8', color: '#854d0e', label: '🍗 Frango' },
    porco:      { bg: '#fdf4ff', color: '#7e22ce', label: '🥓 Porco' },
    peixe:          { bg: '#eff6ff', color: '#1e40af', label: '🐟 Peixe' },
    'frutos do mar': { bg: '#ecfeff', color: '#0e7490', label: '🦐 Frutos do Mar' },
    congelados: { bg: '#f0f9ff', color: '#0369a1', label: '🧊 Congelados' },
    'pães':     { bg: '#fff7ed', color: '#9a3412', label: '🍞 Pães' },
    sopa:       { bg: '#fef9c3', color: '#854d0e', label: '🍲 Sopa' },
    massas:     { bg: '#fdf2f8', color: '#86198f', label: '🍝 Massas' },
    proteina:   { bg: '#f0fdf4', color: '#15803d', label: '💪 Proteína' },
    outro:      { bg: '#f8fafc', color: '#475569', label: '📦 Outro' },
  },
  radius: {
    sm: '6px',
    md: '10px',
    lg: '16px',
  },
  shadow: {
    sm: '0 1px 3px rgba(0,0,0,0.08)',
    md: '0 4px 12px rgba(0,0,0,0.10)',
  },
};
